### ISSUE TITLE
Migrate off planetscale

### ISSUE THREAD

**Issue by mcmc101001** [mcmc101001/StudyStash#305]
Planetscale is ending its free tier, would need to migrate to a different database

**Comment by marquestye** [comment]
AWS S3 free tier will also expire after 12 months which is in May :(

**Comment by mcmc101001** [comment]
@marquestye can u check how much storage is in the s3 bucket (under metrics button) pricing is 2.5 cents per gb per month so we might be able to get free

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.

**Comment by mcmc101001** [comment]
successfully migrated to aiven
